function FunDy = systemOdeJac(in1)
%SYSTEMODEJAC
%    FUNDY = SYSTEMODEJAC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    01-Mar-2018 12:12:07

L = in1.L;
c = in1.c;
g = in1.g;
k = in1.k;
m = in1.m;
t2 = 1.0./m;
t3 = 1.0./L;
t4 = g.*m.*3.0;
FunDy = reshape([0.0,0.0,0.0,k.*t2.*t3.*-3.0,0.0,0.0,t2.*(t4+L.*k.*2.0).*(1.0./3.0),-t2.*t3.*(t4+L.*k.*4.0),1.0,0.0,c.*t2.*(-1.0./3.0),-c.*t2.*t3,0.0,1.0,L.*c.*t2.*(1.0./3.0),c.*t2.*-2.0],[4,4]);
